--Задание 5
DECLARE @tn nvarchar(20), @tc1 nvarchar(20), @tk int;
DECLARE AUDITOR cursor local dynamic
for select AUDITORIUM.AUDITORIUM,AUDITORIUM.AUDITORIUM_TYPE,AUDITORIUM.AUDITORIUM_CAPACITY FROM AUDITORIUM for update;
OPEN AUDITOR;
fetch AUDITOR into @tn,@tc1,@tk;
DELETE AUDITORIUM where CURRENT OF AUDITOR;
fetch AUDITOR into @tn,@tc1,@tk;
UPDATE AUDITORIUM set AUDITORIUM_CAPACITY = AUDITORIUM_CAPACITY + 5 where CURRENT OF AUDITOR;
CLOSE AUDITOR;


--Задание 6
select PROGRESS.NOTE,STUDENT.NAME,GROUPS.IDGROUP FROM GROUPS inner join STUDENT 
on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT where (PROGRESS.NOTE < 7)

DECLARE @nt int,@st nvarchar(20), @gr int;
DECLARE PROGR1 cursor local dynamic
for select PROGRESS.NOTE,STUDENT.NAME,GROUPS.IDGROUP FROM GROUPS inner join STUDENT 
on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT where (PROGRESS.NOTE < 7)  FOR UPDATE;
OPEN PROGR1;
fetch PROGR1 into @nt,@st,@gr ;
--DELETE PROGRESS where CURRENT OF PROGR1;
close PROGR1

select PROGRESS.NOTE,STUDENT.NAME,GROUPS.IDGROUP,STUDENT.IDSTUDENT FROM GROUPS inner join STUDENT 
on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT where (PROGRESS.IDSTUDENT in (1002))

DECLARE @nt1 int,@st1 nvarchar(20), @gr1 int;
DECLARE PROGR1 cursor local dynamic
for select PROGRESS.NOTE,STUDENT.NAME,GROUPS.IDGROUP FROM GROUPS inner join STUDENT 
on GROUPS.IDGROUP = STUDENT.IDGROUP inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT where (PROGRESS.IDSTUDENT  = (1002))  FOR UPDATE;
OPEN PROGR1;
fetch PROGR1 into @nt1,@st1,@gr1 ;
UPDATE PROGRESS set NOTE = NOTE + 1 where CURRENT OF PROGR1;
close PROGR1

