--«‡‰‡ÌËÂ 7
SELECT F.FACULTY,G.PROFESSION,P.SUBJECT, ROUND(AVG(CAST(NOTE AS FLOAT(4))),2) AVG_
FROM FACULTY F JOIN GROUPS G ON G.FACULTY = F.FACULTY JOIN STUDENT S ON S.IDGROUP = G.IDGROUP
JOIN PROGRESS P  ON P.IDSTUDENT = S.IDSTUDENT WHERE F.FACULTY = '»ƒËœ'
GROUP BY G.PROFESSION,P.SUBJECT,F.FACULTY
	UNION
SELECT F.FACULTY,G.PROFESSION,P.SUBJECT, ROUND(AVG(CAST(NOTE AS FLOAT(4))),2) AVG_
FROM FACULTY F JOIN GROUPS G ON G.FACULTY = F.FACULTY JOIN STUDENT S ON S.IDGROUP = G.IDGROUP
JOIN PROGRESS P  ON P.IDSTUDENT = S.IDSTUDENT WHERE F.FACULTY = '’“Ë“'
GROUP BY G.PROFESSION,P.SUBJECT,F.FACULTY



SELECT F.FACULTY,G.PROFESSION,P.SUBJECT, ROUND(AVG(CAST(NOTE AS FLOAT(4))),2) AVG_
FROM FACULTY F JOIN GROUPS G ON G.FACULTY = F.FACULTY JOIN STUDENT S ON S.IDGROUP = G.IDGROUP
JOIN PROGRESS P  ON P.IDSTUDENT = S.IDSTUDENT WHERE F.FACULTY = '»ƒËœ'
GROUP BY G.PROFESSION,P.SUBJECT,F.FACULTY
	UNION ALL
SELECT F.FACULTY,G.PROFESSION,P.SUBJECT, ROUND(AVG(CAST(NOTE AS FLOAT(4))),2) AVG_
FROM FACULTY F JOIN GROUPS G ON G.FACULTY = F.FACULTY JOIN STUDENT S ON S.IDGROUP = G.IDGROUP
JOIN PROGRESS P  ON P.IDSTUDENT = S.IDSTUDENT WHERE F.FACULTY = '’“Ë“'
GROUP BY G.PROFESSION,P.SUBJECT,F.FACULTY
