--Задание 1
SELECT min(AUDITORIUM_CAPACITY) [MINIMAL CAPACITY],
max(AUDITORIUM_CAPACITY) [MAXIMAL],
AVG(AUDITORIUM_CAPACITY) [AVERAGE],
sum(AUDITORIUM_CAPACITY) [SUM],
count(*) [COUNT]
FROM AUDITORIUM;

--Задание 2
SELECT  AUDITORIUM_TYPENAME [AUDITORIUM_TYPENAME],
min(AUDITORIUM_CAPACITY) [MINIMAL CAPACITY],
max(AUDITORIUM_CAPACITY) [MAXIMAL],
AVG(AUDITORIUM_CAPACITY) [AVERAGE],
sum(AUDITORIUM_CAPACITY) [SUM],
count(*) [COUNT]
FROM AUDITORIUM_TYPE INNER JOIN AUDITORIUM
ON AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE
GROUP BY  AUDITORIUM_TYPENAME