--Задание 5
SELECT F.FACULTY, G.PROFESSION, P.SUBJECT,ROUND(AVG(CAST(NOTE AS FLOAT(4))),2) AVG_MARK
FROM FACULTY F
JOIN GROUPS G ON F.FACULTY = G.FACULTY
JOIN STUDENT S ON S.IDGROUP = G.IDGROUP
JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
WHERE F.FACULTY = 'ИДиП'
GROUP BY F.FACULTY, G.PROFESSION , P.SUBJECT

SELECT F.FACULTY, G.PROFESSION, P.SUBJECT,ROUND(AVG(CAST(NOTE AS FLOAT(4))),2) AVG_MARK
FROM FACULTY F
JOIN GROUPS G ON F.FACULTY = G.FACULTY
JOIN STUDENT S ON S.IDGROUP = G.IDGROUP
JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
WHERE F.FACULTY = 'ИДиП' 
GROUP BY ROLLUP( F.FACULTY, G.PROFESSION , P.SUBJECT)

--Задание 6
SELECT F.FACULTY, G.PROFESSION, P.SUBJECT,ROUND(AVG(CAST(NOTE AS FLOAT(4))),2) AVG_MARK
FROM FACULTY F
JOIN GROUPS G ON F.FACULTY = G.FACULTY
JOIN STUDENT S ON S.IDGROUP = G.IDGROUP
JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
WHERE F.FACULTY = 'ИДиП' 
GROUP BY CUBE( F.FACULTY, G.PROFESSION , P.SUBJECT)


