--Задание 8
SELECT G.PROFESSION,P.SUBJECT, ROUND(AVG(CAST(NOTE AS FLOAT(4))),2) AVG_
FROM FACULTY F JOIN GROUPS G ON G.FACULTY = F.FACULTY JOIN STUDENT S ON S.IDGROUP = G.IDGROUP
JOIN PROGRESS P  ON P.IDSTUDENT = S.IDSTUDENT WHERE F.FACULTY = 'ХТиТ'
GROUP BY G.PROFESSION,P.SUBJECT
	INTERSECT 
SELECT G.PROFESSION,P.SUBJECT, ROUND(AVG(CAST(NOTE AS FLOAT(4))),2) AVG_
FROM FACULTY F JOIN GROUPS G ON G.FACULTY = F.FACULTY JOIN STUDENT S ON S.IDGROUP = G.IDGROUP
JOIN PROGRESS P  ON P.IDSTUDENT = S.IDSTUDENT WHERE F.FACULTY = 'ИДиП'
GROUP BY G.PROFESSION,P.SUBJECT

--Задание 9
SELECT G.PROFESSION,P.SUBJECT, ROUND(AVG(CAST(NOTE AS FLOAT(4))),2) AVG_
FROM FACULTY F JOIN GROUPS G ON G.FACULTY = F.FACULTY JOIN STUDENT S ON S.IDGROUP = G.IDGROUP
JOIN PROGRESS P  ON P.IDSTUDENT = S.IDSTUDENT WHERE F.FACULTY = 'ИДиП'
GROUP BY G.PROFESSION,P.SUBJECT
	EXCEPT 
SELECT G.PROFESSION,P.SUBJECT, ROUND(AVG(CAST(NOTE AS FLOAT(4))),2) AVG_
FROM FACULTY F JOIN GROUPS G ON G.FACULTY = F.FACULTY JOIN STUDENT S ON S.IDGROUP = G.IDGROUP
JOIN PROGRESS P  ON P.IDSTUDENT = S.IDSTUDENT WHERE F.FACULTY = 'ХТиТ'
GROUP BY G.PROFESSION,P.SUBJECT

--Задание 10
SELECT P.NOTE, P.SUBJECT FROM PROGRESS P
SELECT P1.SUBJECT, P1.NOTE,
(SELECT COUNT(*) FROM PROGRESS P2 WHERE P2.SUBJECT = P1.SUBJECT AND P2.NOTE  = P1.NOTE) CNT
FROM PROGRESS P1
GROUP BY P1.SUBJECT, P1.NOTE
HAVING P1.NOTE = 8 OR P1.NOTE = 9

