--Задание 3
SELECT *  FROM (SELECT CASE WHEN P.NOTE IN(10) THEN '10'
			WHEN P.NOTE BETWEEN 8 AND 9 THEN '8-9'
			WHEN P.NOTE BETWEEN 6 AND 7 THEN '6-7'
			WHEN P.NOTE BETWEEN 4 AND 5 THEN '4-5'
			ELSE '<4'
			END [NOTES], COUNT(*) [COUNT] 
		FROM PROGRESS P GROUP BY CASE WHEN P.NOTE IN(10) THEN '10'
			WHEN P.NOTE BETWEEN 8 AND 9 THEN '8-9'
			WHEN P.NOTE BETWEEN 6 AND 7 THEN '6-7'
			WHEN P.NOTE BETWEEN 4 AND 5 THEN '4-5'
			ELSE '<4'
			END ) AS T
		ORDER BY CASE NOTES WHEN '10' THEN 0
			WHEN '8-9' THEN 1
			WHEN '6-7' THEN 2
			WHEN '4-5' THEN 3
			ELSE 4
			END
			
--Задание 4
SELECT FACULTY.FACULTY[FACULTY], PROFESSION[PROFESSION], SUBJECT, round(avg(cast(NOTE as float)),2)[AVG_MARK]
FROM FACULTY INNER JOIN GROUPS ON FACULTY.FACULTY=GROUPS.FACULTY
INNER JOIN STUDENT ON STUDENT.IDGROUP=GROUPS.IDGROUP
INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT=STUDENT.IDSTUDENT
GROUP BY YEAR_FIRST,FACULTY.FACULTY,PROFESSION,SUBJECT
ORDER BY [AVG_MARK] DESC 

SELECT FACULTY.FACULTY[FACULTY], PROFESSION[PROFESSION], SUBJECT, round(avg(cast(NOTE as float)),2)[AVG_MARK]
FROM FACULTY INNER JOIN GROUPS ON FACULTY.FACULTY=GROUPS.FACULTY
INNER JOIN STUDENT ON STUDENT.IDGROUP=GROUPS.IDGROUP
INNER JOIN PROGRESS ON PROGRESS.IDSTUDENT=STUDENT.IDSTUDENT
WHERE PROGRESS.SUBJECT IN ('СУБД','ОАиП')
GROUP BY YEAR_FIRST,FACULTY.FACULTY,PROFESSION,SUBJECT
ORDER BY [AVG_MARK] DESC

