use Univer

SELECT PULPIT.PULPIT_NAME, FACULTY.FACULTY_NAME from FACULTY, PULPIT  where PULPIT.FACULTY = FACULTY.FACULTY
	and PULPIT.FACULTY in (select FACULTY from PROFESSION where (PROFESSION_NAME like '%технология%') or (PROFESSION_NAME like '%технологии%')) ;

SELECT PULPIT.PULPIT_NAME from PULPIT inner join FACULTY on PULPIT.FACULTY = FACULTY.FACULTY
	and FACULTY.FACULTY in (select FACULTY from PROFESSION where (PROFESSION_NAME like '%технология%') or (PROFESSION_NAME like '%технологии%')) ;

SELECT PULPIT.PULPIT_NAME from PULPIT inner join FACULTY on PULPIT.FACULTY = FACULTY.FACULTY inner join PROFESSION on PULPIT.FACULTY = PROFESSION.FACULTY
	where (PROFESSION.PROFESSION_NAME like '%технология%') or (PROFESSION.PROFESSION_NAME like '%технологии%');