use Univer

select PROGRESS.NOTE, PROGRESS.SUBJECT, STUDENT.NAME, FACULTY.FACULTY, PULPIT.PULPIT, PROFESSION.PROFESSION,

case
when (PROGRESS.NOTE = 6)then 'шесть'
when (PROGRESS.NOTE = 7)then 'семь'
else 'восемь' end [оценка]

from FACULTY inner join PULPIT 
on FACULTY.FACULTY=PULPIT.FACULTY inner join PROFESSION
on PULPIT.FACULTY = PROFESSION.FACULTY inner join GROUPS
on PROFESSION.PROFESSION=GROUPS.PROFESSION inner join STUDENT
on GROUPS.IDGROUP=STUDENT.IDGROUP inner join PROGRESS
on STUDENT.IDSTUDENT=PROGRESS.IDSTUDENT where PROGRESS.NOTE between 6 and 8

order by 
FACULTY.FACULTY desc, PULPIT.PULPIT desc, PROFESSION.PROFESSION desc, STUDENT.NAME desc, PROGRESS.NOTE asc
--(case when (PROGRESS.NOTE = 6) then 3
--when (PROGRESS.NOTE = 7) then 1
--else 2 end)

