use Univer
select AUDITORIUM, AUDITORIUM_TYPENAME from AUDITORIUM Inner Join AUDITORIUM_TYPE 
on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

select AUDITORIUM, AUDITORIUM_TYPENAME from AUDITORIUM, AUDITORIUM_TYPE 
Where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE